language: generic
sudo: required
services:
  - docker

before_install:
  - cd calc-app
  - docker build -t bouquineuse/calc-app -f Dockerfile.dev .

script:
  - docker run -e CI=true bouquineuse/calc-app npm run test:ci
